services:
  challenge-api:
    image: redteamsubnet61/rest-aad-challenge:2.0.3
    build:
      context: ./src/aad_challenge/challenge
    restart: unless-stopped
    platform: linux/amd64
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      AAD_CHALLENGE_API_PORT: ${AAD_CHALLENGE_API_PORT:-10001}
      AAD_API_PORT: ${AAD_API_PORT:-10001}
      AAD_API_CONFIGS_DIR: ${AAD_API_CONFIGS_DIR:-/etc/rest-aad-challenge}
      AAD_API_LOGS_DIR: ${AAD_API_LOGS_DIR:-/var/log/rest-aad-challenge}
      AAD_API_DATA_DIR: ${AAD_API_DATA_DIR:-/var/lib/rest-aad-challenge}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/configs/rest-aad-challenge:${AAD_API_CONFIGS_DIR:-/etc/rest-aad-challenge}"
      - "./volumes/storage/rest-aad-challenge/logs:${AAD_API_LOGS_DIR:-/var/log/rest-aad-challenge}"
      - "./volumes/storage/rest-aad-challenge/data:${AAD_API_DATA_DIR:-/var/lib/rest-aad-challenge}"
    ports:
      - "${AAD_CHALLENGE_API_PORT:-10001}:${AAD_CHALLENGE_API_PORT:-10001}"
    tty: true
