challenge:
  api_key: "challenge_api_key"
  docker_ulimit: 32768
  bot_timeout: 10
  repeated_framework_count: 3
  human_injection_count: 6
  allowed_human_miss_count: 1
  allowed_webdriver_miss_count: 2
  allowed_websocket_miss_count: 2
  nstbrowser:
    api_key: "nstbrowser_api_key"
    host: "localhost"
    port: 8848
    protocol: "http"
  verification:
    endpoint: "http://challenge_server:8000/api/v1/verify"
    api_key: "super_secure_api_key"
    startup_url: "http://challenge_server:8000/start"
    extra:
      platform: "Linux"
      autoClose: false
      headless: true
      incognito: true
      fingerprintRandomness: true
      fingerprinting:
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.6998.45 Safari/537.36"
        deviceMemory: 8
        hardwareConcurrency: 16
        screen:
          width: 1280
          height: 1024
      args:
        "--disable-backgrounding-occluded-windows": true
        "--disable-blink-features": "AutomationControlled"
        "--no-sandbox": true
        "--disable-infobars": true
        "--user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.6998.45 Safari/537.36"
  framework_images:
    - name: nodriver
      image: redteamsubnet61/aad_nodriver@sha256:440916fe1800caf483a9105d484e2570672e74a5910afc5955c6aff7528a5d44
    - name: playwright
      image: redteamsubnet61/aad_playwright@sha256:96bf78cf38824d58099a44183625bc5923c4d3a2d2baa42a77fe8da0cb654a31
    - name: patchright
      image: redteamsubnet61/aad_patchright@sha256:34a5593c21c4a246476def8c0fefb2123c067de5c93189b9c4889dfe7b7d0e1d
    - name: puppeteer
      image: redteamsubnet61/aad_puppeteer@sha256:7460857027ef130f4bfee528a0cfb891d4c6a0f7bfc6480749562ad7070dd1b6
    - name: puppeteer_extra
      image: redteamsubnet61/aad_puppeteerextra@sha256:4785eeb40873588369a779a8c79bb5ce9f11b182721c7a8c96c331bfb75e953a
    - name: zendriver
      image: redteamsubnet61/aad_zendriver@sha256:9e914a92d31712047df2a8389d2dddf859092bd4394e8361e23e1f241a56f9da
    - name: selenium_driverless
      image: redteamsubnet61/aad_selenium_driverless@sha256:2e34ea141ce76cd06ad326fda2e276872716801c0bbfb2a7794d7bbc9536b5f2
    - name: seleniumbase
      image: redteamsubnet61/aad_seleniumbase@sha256:7b0d96e47ec0b89bb8330c6663731f44cbaa4ba7ef03bf3ba05a7a2a9fd599cf
